### ISSUE TITLE
请问Manager API 中注册账户的密码是怎么操作的？

### ISSUE THREAD

**Issue by Lazercloud** [yushijinhun/authlib-agent#1]
请问Manager API 中注册账户的密码是怎么操作的？

**Comment by yushijinhun** [comment]
抱歉哈，貌似忘记在wiki上说明了。密码的话，需要在请求体内包含：

``` json
"password": "<明文密码>"
```

**Comment by yushijinhun** [comment]
Fixed in commit [0a14a86fe00b96de11610e258d222a5e40d51270](https://github.com/to2mbn/authlib-agent/wiki/Manager-API/_compare/da614cd86fa42db1f54a797795db304e88cad37b...0a14a86fe00b96de11610e258d222a5e40d51270).
Closing this issue.
