### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by Curtain2312** [yushijinhun/authlib-agent#10]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project yggdrasil-backend: Compilation failure
[ERROR] /root/authlib-agent/yggdrasil-backend/src/main/java/yushijinhun/authlibagent/web/manager/LoginResourceImpl.java:[15,10] cannot find symbol
[ERROR] symbol:   class Transactional
[ERROR] location: class yushijinhun.authlibagent.web.manager.LoginResourceImpl
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :yggdrasil-backend

**Comment by yushijinhun** [comment]
噗。。我刚刚在外面，手机上改的，没测试

**Comment by Curtain2312** [comment]
表示不懂Java如果是PHP我就帮你改了嘿嘿

**Comment by yushijinhun** [comment]
我下周有一个非常重要的考试，会很忙，所以这个项目肯定就暂时不管了。如果还有什么bug的话我也得下下个星期再处理了。

**Comment by Curtain2312** [comment]
好 我最近也要转战JAVA如果我能修我就帮你修了
