### ISSUE TITLE
使用API注册中文角色时报错

### ISSUE THREAD

**Issue by l89669** [yushijinhun/authlib-agent#11]
// POST 注册到/api/accounts
curl -l -H "Content-type: application/json" -X POST -d '{"id" : "l89669@hotmail.com", "password": "l89669"}' http://s1.summermc.top:8080/yggdrasil-backend/api/accounts
// 结果
{
  "id" : "l89669@hotmail.com",
  "banned" : false,
  "twitchToken" : "",
  "profiles" : [ ]
}

// POST 角色创建到/api/profiles
curl -l -H "Content-type: application/json; charset=utf-8" -X POST -d '{"name" : "徘徊丶丶", "owner" : "l89669@hotmail.com"}' http://s1.summermc.top:8080/yggdrasil-backend/api/profiles
// 结果
{
  "errorCode" : 400,
  "error" : "JsonMappingException: Invalid UTF-8 middle byte 0xc7\n at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@a950e29; line: 1, column: 14]\n at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@a950e29; line: 1, column: 11] (through reference chain: yushijinhun.authlibagent.web.manager.ProfileInfo[\"name\"])"
}

**Comment by yushijinhun** [comment]
我这边无法重现这个异常，你确定请求用的是utf8编码？

**Comment by l89669** [comment]
非常抱歉给您带来打扰，的确是我的编码问题，在linux机器上测试就不报错了，只有在win上报错

**Comment by l89669** [comment]
@yushijinhun 为什么我手动POST会出现如下的错误，求教

// POST请求
`curl -l -H "Content-type: application/json; charset=utf8" -X POST -d '{"agent": {"name": "Minecraft", "version": 1 }, "username": "l89669@hotmail.com", "password": "l89669", "requestUser": true }' http://s1.summermc.top:8080/yggdrasil-backend/authenticate`

// 结果
`<html><body>No service was found.</body></html>`

附注: http://s1.summermc.top:8080/yggdrasil-backend/api/accounts 可以正常访问

**Comment by yushijinhun** [comment]
应该是`http://s1.summermc.top:8080/yggdrasil-backend/yggdrasil/authenticate`，漏了个`/yggdrasil`
另外我指出一点，`/yggdrasil`是对外提供服务的，`/api`应该是你内部用的api。所以`/api`对外开放有很大的安全隐患。这个我在[wiki](https://github.com/to2mbn/authlib-agent/wiki/Deployment-Guide#%E9%85%8D%E7%BD%AEapachenginx)是说过的。

**Comment by l89669** [comment]
非常感谢您的帮助，已经解决了，api接口也对外隐藏了
建议在未来版本中对api接口加入accessKey来进一步确保安全

ps. 有时候会出现莫名的Mysql timeout，再访问一次就好了，是程序问题还是数据库问题？（数据库给authme和coreprotect用一直没问题）
