### ISSUE TITLE
是否可以实现对原正版登录的兼容？

### ISSUE THREAD

**Issue by LinEvil** [yushijinhun/authlib-agent#13]
RT，设想是对非正版玩家要求使用自有的用户系统，正版玩家则使用MOJANG的用户系统。
若两者存在冲突则以第一次进入服务器的时间先后为准。

**Comment by yushijinhun** [comment]
这个是可行的。不过我要中考了所以估计也没有时间做。

**Comment by LinEvil** [comment]
你能描述一下大概的实现吗？
我有点迷糊。

**Comment by l89669** [comment]
感觉不大好，如果想服务器兼容两种用户可以从服务端插件入手，比如fastlogin
在启动器兼容方面，我倒是已经给hmcl写了一个插件，可以不使用javaagent，而是作为一个独立的验证方式（和离线验证，正版登陆并列）加入进启动器里面

**Comment by l89669** [comment]
当然也可以在api上添加一个“标记为正版用户”的功能，post该用户的正版id和密码到服务器上（这样不太安全），一旦用户被标记为正版，登陆时authenticate页面就向mojang转发，并将请求到的accesskey缓存到服务器本地，让使用javaagent的服务器在验证时也能读取到
但是并不清楚转发这一过程会不会被mojang认定为vpn从而带来封号风险

**Comment by yushijinhun** [comment]
你的意思是，只要满足客户端是正版用户，或客户端使用自有的账户系统，那么就可以登录成功。如果客户端是正版用户，那么登录流程中，我们可以控制的部分就是进服验证这一块。这部分的流程如下（服务端加载了authlibagent，而客户端没有，所以前者将请求发往自有的验证系统，后者将请求发往mojang）：
   1. 服务端随机生成一段字符串，发送给客户端
   2. 客户端调用**mojang**的`joinServer`api，字符串包含在请求中
   3. 服务端调用**自有验证系统**的`hasJoinedServer`api，字符串包含在请求中

上面流程的意义我不多讲，wiki.vg上有很详细的介绍。那我们现在找问题，为什么我们不能达到`如果客户端是正版用户，也可以登录成功`这个目的。可以发现，`joinServer`和`hasJoinedServer`两个请求不是被发送到同一账户系统的，这就造成了自有账户系统上没有客户端调用`joinServer`的记录，进而造成登录失败。那么解决办法也就出来了：在后端处理`hasJoinedServer`请求时，如果没有对应`joinServer`的记录，就再向mojang请求。

除此之外，还有另一个地方需要改动：后端收到查询GameProfile的请求时，如果数据库中没有查到，则要再向mojang查询，然后把其中textures部分的数字签名换成自己的，再返回。

**Comment by LinEvil** [comment]
没错，我就是这个意思。
感谢dalao。

**Comment by yushijinhun** [comment]
我中考回来了，准备做这个功能。
