### ISSUE TITLE
无法连接到jedis: connection refused

### ISSUE THREAD

**Issue by l89669** [yushijinhun/authlib-agent#15]
redis我设置的无密码，端口开放给公网
搭建的yggdrasil-backend很久没用过了，redis也很久没动过了，今天想登录突然就提示redis连接不上(connection refused)
调试了n久，我在自己计算机上开发时用redis-cli还是jedis都能连接上同一个服务器，就是搭建的服务连接不上redis(值得一提的是在同台机器上的blesding skin也能连接上)
反正就是一众程序都能连接上，只有这个服务报错连接不上
大佬别嫌萌新问题多，还烦请帮我一下，看看到底怎么回事

**Comment by Hookan** [comment]
首先，不论redis是否有密码，都不应该对公网开放。
然后请你仔细检查redis的ip和端口是否设置正确，防火墙是否配置正确。
如果问题还存在，请你提供更多有用的信息。

**Comment by l89669** [comment]
我只是为了测试redis服务器的正常工作短暂开放了公网访问，而且在防火墙中配置了ip白名单，另外，如果我设置的不正确没道理别的程序用同样的端口能连接上啊，只有spring不行，实在是太奇怪了，除了自带的application那个配置文件以外还有其他配置redis的地方吗？

**Comment by yushijinhun** [comment]
你说你很久以前就配置好了，现在突然无法连接上redis。如果原来能正常工作的话，你检查一下在这期间有没有什么变化的地方，如服务器ip等等。

redis在configure.sh里配置即可，构建的时候会把参数填到application.xml里。

**Comment by l89669** [comment]
是在没动任何配置的情况下重启了一下tomcat，就连不上了，重启前是能连上的
我已经放弃tomcat了，服务端我选择去用了blessing skin server的yggdrasil插件，但是发生了另一个错误，我已经又提了一个issue了

**Comment by l89669** [comment]
已解决，重装了redis
