### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by mcoo** [yushijinhun/authlib-agent#18]
`编译出现
[code][ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] authlib-agent-parent ............................... SUCCESS [  5.930 s]
[INFO] authlib-javaagent .................................. FAILURE [  1.591 s]
[INFO] yggdrasil-backend .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.913 s
[INFO] Finished at: 2017-08-18T21:11:07+08:00
[INFO] Final Memory: 11M/28M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project authlib-javaagent: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :authlib-javaagent

cp: 无法获取"./authlib-javaagent/target/authlib-javaagent-*-jar-with-dependencies.jar" 的文件状态(stat): 没有那个文件或目录
./authlib-javaagent/target/authlib-javaagent-*-jar-with-dependencies.jar is saved to authlibagent.jar
cp: 无法获取"./yggdrasil-backend/target/yggdrasil-backend-*.war" 的文件状态(stat): 没有那个文件或目录
./yggdrasil-backend/target/yggdrasil-backend-*.war is saved to yggdrasil-backend.war
[/code]
`

**Comment by 5aaee9** [comment]
请确认安装了JDK 如果已经安装 尝试设置 JAVA_HOME 的环境变量

**Comment by yushijinhun** [comment]
请确认你安装的是JDK而不是JRE，并且`JAVA_HOME`已正确配置。
