### ISSUE TITLE
现在的服务端认证地址变了？

### ISSUE THREAD

**Issue by ChenhaoShen** [yushijinhun/authlib-agent#19]
06-Dec-2017 21:47:47.023 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Yggdrasil]
06-Dec-2017 21:47:47.024 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.24
06-Dec-2017 21:47:47.026 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/data/Program/tomcat-8.5.24/webroot/yggdrasil/yggdrasil-backend-0.0.1-SNAPSHOT.war]
06-Dec-2017 21:47:47.421 INFO [pool-6-thread-11] jenkins.InitReactorRunner$1.onAttained Prepared all plugins
06-Dec-2017 21:47:47.422 INFO [PluginImpl.init] jenkins.InitReactorRunner$1.onAttained Started all plugins
06-Dec-2017 21:47:49.270 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
06-Dec-2017 21:47:49.599 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
06-Dec-2017 21:47:49.628 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
06-Dec-2017 21:47:49.919 INFO [CustomOrganizationFolderDescriptor.addSpecificDescriptors] hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.error Failed to instantiate optional component hudson.plugins.build_timeout.operations.AbortAndRestartOperation$DescriptorImpl; skipping
06-Dec-2017 21:47:50.719 INFO [pool-6-thread-15] jenkins.InitReactorRunner$1.onAttained Augmented all extensions
06-Dec-2017 21:47:51.043 INFO [pool-6-thread-3] jenkins.InitReactorRunner$1.onAttained Loaded all jobs
06-Dec-2017 21:47:51.054 INFO [Download metadata thread] hudson.model.AsyncPeriodicWork$1.run Started Download metadata
06-Dec-2017 21:47:51.331 INFO [pool-6-thread-6] jenkins.InitReactorRunner$1.onAttained Completed initialization
06-Dec-2017 21:47:51.333 INFO [Download metadata thread] hudson.model.AsyncPeriodicWork$1.run Finished Download metadata. 276 ms
06-Dec-2017 21:47:52.144 INFO [Finalizing set up] org.springframework.context.support.AbstractApplicationContext.prepareRefresh Refreshing org.springframework.web.context.support.StaticWebApplicationContext@544c96c7: display name [Root WebApplicationContext]; startup date [Wed Dec 06 21:47:52 CST 2017]; root of context hierarchy
06-Dec-2017 21:47:52.144 INFO [Finalizing set up] org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@544c96c7]: org.springframework.beans.factory.support.DefaultListableBeanFactory@378ff47f
06-Dec-2017 21:47:52.158 INFO [Finalizing set up] org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@378ff47f: defining beans [authenticationManager]; root of factory hierarchy
06-Dec-2017 21:47:52.425 INFO [Finalizing set up] org.springframework.context.support.AbstractApplicationContext.prepareRefresh Refreshing org.springframework.web.context.support.StaticWebApplicationContext@4dc02125: display name [Root WebApplicationContext]; startup date [Wed Dec 06 21:47:52 CST 2017]; root of context hierarchy
06-Dec-2017 21:47:52.425 INFO [Finalizing set up] org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@4dc02125]: org.springframework.beans.factory.support.DefaultListableBeanFactory@37923c1b
06-Dec-2017 21:47:52.426 INFO [Finalizing set up] org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@37923c1b: defining beans [filter,legacy]; root of factory hierarchy
06-Dec-2017 21:47:52.549 INFO [Jenkins initialization thread] hudson.WebAppMain$3.run Jenkins is fully up and running
06-Dec-2017 21:47:53.947 INFO [localhost-startStop-1] org.apache.cxf.endpoint.ServerImpl.initDestination Setting the server's publish address to be /api
06-Dec-2017 21:47:54.176 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/data/Program/tomcat-8.5.24/webroot/yggdrasil/yggdrasil-backend-0.0.1-SNAPSHOT.war] has finished in [7,150] ms
06-Dec-2017 21:47:54.178 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-50001"]
06-Dec-2017 21:47:54.182 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 25737 ms
06-Dec-2017 21:48:44.450 WARNING [http-nio-50001-exec-2] org.apache.cxf.transport.servlet.ServletController.invoke Can't find the the request for http://localhost:50001/yggdrasil-backend-0.0.1-SNAPSHOT/yggdrasil/'s Observer 

不是原来的 /yggdrasil 了？

**Comment by yushijinhun** [comment]
你需要把.war命名为ROOT.war，这样app才会在/下。
