### ISSUE TITLE
new api cause cant run backend

### ISSUE THREAD

**Issue by zMCdarc** [yushijinhun/authlib-agent#3]
file ...src/main/java/yushijinhun/authlibagent/web/yggdrasil/servlet/Username2ProfileServlet.java 

-@WebServlet("/yggdrasil/profiles/minecraft/*")
+@WebServlet("/yggdrasil/user/profiles/minecraft/*")

can fix it

哎都是中国人说啥英语

**Comment by yushijinhun** [comment]
Fixed in f0761959158fc64a71db6d197747946e7cad20cf
