### ISSUE TITLE
[Question]关于验证用户的问题

### ISSUE THREAD

**Issue by Genteure** [yushijinhun/authlib-agent#4]
我目前在考虑使用此项目做玩家账号的管理，但是想实现在服务器内登录。而不是通过重定向正版登录请求地址的方式（伪正版登录、外置登录）。
使用重定向正版登录请求的方法，就需要自己提供游戏启动器给玩家，目前暂时不需要这个功能（以后可能会需要）
所以想问一下，在 /api 下有没有提供验证玩家用户名和密码的接口（wiki中没有看到，问下确认下），或者我自己读数据库做验证的话，应该怎么做。
谢谢

**Comment by yushijinhun** [comment]
这是做不到的。如果你要使用authlib-agent的话，就意味着你的登录流程和正版登录是基本一样的，差别只在于负责处理验证的服务器是你的还是mojang的。而如果你要修改这一流程，使得游戏外登录变为游戏内登录，会有非常多的问题。具体我不一一举例，你可以自己列表对比，会发现两者完全是不同的。如果说你要游戏内登录的话，推荐authme。

**Comment by Genteure** [comment]
目前最想要做到的效果是保证能为每个玩家分配一个固定的UUID，防止以后服务器需要修改东西的时候UUID和玩家名对不上号。
基本思路是自己写BC插件，修改玩家对应的 `net.md_5.bungee.connection.InitialHandler` 中的UUID，然后再把玩家送入子服务器（已测试，基本思路没有问题）
为了以后拓展，打算使用此项目管理玩家账号
如果确实没有办法的话，打算自己写一套相对更简单些的账户系统，只实现最想要的“固定玩家UUID”。
我觉得是可以试一下的。

**Comment by Genteure** [comment]
即使不是游戏内验证这样的需求，在其他地方也是会有验证用户名密码的需求的，比如网站登录。验证用户名密码还是需要的

**Comment by yushijinhun** [comment]
我给这个功能开了个issue #5 。

不过你这个idea我觉得做起来挺悬的。

**Comment by Genteure** [comment]
好的，谢谢

**Comment by yushijinhun** [comment]
api已添加，文档在：https://github.com/to2mbn/authlib-agent/wiki/Manager-API#%E7%99%BB%E5%BD%95%E8%B4%A6%E6%88%B7

**Comment by Genteure** [comment]
好的，感谢
