### ISSUE TITLE
hack之后的一些问题

### ISSUE THREAD

**Issue by Curtain2312** [yushijinhun/authlib-agent#7]
1.hack hcml启动器只能在第一次登陆的时候获取角色 再次打开就会提示没有角色 得退出账号重新获取
2.hack了Thermos-1.7.10服务端 开启了在线模式 但是登入游戏 提示无效的会话

**Comment by yushijinhun** [comment]
你有没有给minecraft加参数？

**Comment by Curtain2312** [comment]
没有

**Comment by yushijinhun** [comment]
见https://github.com/to2mbn/authlib-agent/wiki/Deployment-Guide#%E5%9C%A8%E5%90%AF%E5%8A%A8%E5%99%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%B8%AD%E5%8A%A0%E8%BD%BDauthlibagent
```
authlibagent.jar适用于所有java编写(或jvm语言编写)的启动器/客户端/服务端等, 需要在启动时在JVM参数中加入-javaagent:<authlibagent.jar路径>. 或者可以配置环境变量JAVA_TOOL_OPTIONS, 将其值设为-javaagent:<authlibagent.jar路径>.
```
