### ISSUE TITLE
新建角色有几率出现无法查询到

### ISSUE THREAD

**Issue by Curtain2312** [yushijinhun/authlib-agent#8]
我服务器的玩家新注册的账户 可以查询到账号 但是其账号下的角色无法查询到 但数据库内有 必须得重启tomcat才可以查询到

**Comment by yushijinhun** [comment]
看样子可能是查询缓存没有被正确失效

**Comment by Curtain2312** [comment]
那是我 redis的事？

**Comment by yushijinhun** [comment]
不是，查询缓存是在ehcache里的。
另外，无法查询到是列出的角色里不包含，还是查询它的信息时查不到？

**Comment by Curtain2312** [comment]
查询账号 账号内不含有角色 然后单独查询角色信息也查不到
