### ISSUE TITLE
登录API发生错误

### ISSUE THREAD

**Issue by Curtain2312** [yushijinhun/authlib-agent#9]
错误信息
  "errorCode" : 500,
  "error" : "LazyInitializationException: failed to lazily initialize a collection of role: yushijinhun.authlibagent.model.Account.profiles, could not initialize proxy - no Session"

**Comment by Curtain2312** [comment]
使用的是最新版 就是你修复了#8和一个选角色的BUG的那个版本

**Comment by yushijinhun** [comment]
你是基于哪个commit构建的？在什么请求下出现这个异常？
